
const services = [
    { id: 1, name: 'replace Tire', price: 2000, time: 2, descript: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet velit magna, eget dapibus arcu luctus malesuada. Nam imperdiet ipsum non consectetur condimentum. Donec iaculis blandit tellus, eget mollis leo fermentum nec. Morbi quis porta nunc. Pellentesque eu quam vestibulum, elementum risus sed, blandit tortor.', img: 'https://ibb.co/mhhYxgh' },
    { id: 2, name: 'engine repair', price: 5000, time: 5, descript: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet velit magna, eget dapibus arcu luctus malesuada. Nam imperdiet ipsum non consectetur condimentum. Donec iaculis blandit tellus, eget mollis leo fermentum nec. Morbi quis porta nunc. Pellentesque eu quam vestibulum, elementum risus sed, blandit tortor.', img: 'https://ibb.co/kJKXK84' },
    { id: 3, name: 'cleaning car ', price: 5000, time: 5, descript: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet velit magna, eget dapibus arcu luctus malesuada. Nam imperdiet ipsum non consectetur condimentum. Donec iaculis blandit tellus, eget mollis leo fermentum nec. Morbi quis porta nunc. Pellentesque eu quam vestibulum, elementum risus sed, blandit tortor.', img: 'https://ibb.co/3N273BH' },
    { id: 4, name: 'change mobile car ', price: 5000, time: 5, descript: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet velit magna, eget dapibus arcu luctus malesuada. Nam imperdiet ipsum non consectetur condimentum. Donec iaculis blandit tellus, eget mollis leo fermentum nec. Morbi quis porta nunc. Pellentesque eu quam vestibulum, elementum risus sed, blandit tortor.', img: 'https://ibb.co/b56c6wW' },
    { id: 5, name: 'auto motor ', price: 5000, time: 5, descript: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet velit magna, eget dapibus arcu luctus malesuada. Nam imperdiet ipsum non consectetur condimentum. Donec iaculis blandit tellus, eget mollis leo fermentum nec. Morbi quis porta nunc. Pellentesque eu quam vestibulum, elementum risus sed, blandit tortor.', img: 'https://ibb.co/b56c6wW' },
    { id: 6, name: ' motor bike repair ', price: 5000, time: 5, descript: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet velit magna, eget dapibus arcu luctus malesuada. Nam imperdiet ipsum non consectetur condimentum. Donec iaculis blandit tellus, eget mollis leo fermentum nec. Morbi quis porta nunc. Pellentesque eu quam vestibulum, elementum risus sed, blandit tortor.', img: 'https://ibb.co/FxpFNJ5' },
    { id: 7, name: ' car  body  repair ', price: 5000, time: 5, descript: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet velit magna, eget dapibus arcu luctus malesuada. Nam imperdiet ipsum non consectetur condimentum. Donec iaculis blandit tellus, eget mollis leo fermentum nec. Morbi quis porta nunc. Pellentesque eu quam vestibulum, elementum risus sed, blandit tortor.', img: 'https://ibb.co/qFBNFPr' },
    { id: 8, name: ' bike engine repair ', price: 5000, time: 5, descript: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec imperdiet velit magna, eget dapibus arcu luctus malesuada. Nam imperdiet ipsum non consectetur condimentum. Donec iaculis blandit tellus, eget mollis leo fermentum nec. Morbi quis porta nunc. Pellentesque eu quam vestibulum, elementum risus sed, blandit tortor.', img: 'https://ibb.co/1vwj43p' }
];



